language: android
android:
    components:
        - tools
        - build-tools-25.0.2
        - android-21
        - extra-android-m2repository
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
            - oracle-java8-installer
            - oracle-java8-set-default
before_install:
    - chmod +x gradlew
script:
    - ./gradlew clean build
